"""
generate_supabase_seed.py — Convert drugs_cache.json → Supabase migration SQL.

Why: the live Supabase `drugs` table is empty (the 62-row seed migration was
never applied). With 3,648 drugs in the local cache, we want them in Supabase
so the frontend's Radar Stock + DCI Switch features actually find drugs.

Output: supabase/migrations/<timestamp>_seed_drugs_v2.sql
The user pastes this into Supabase Dashboard → SQL Editor → Run.

Usage:
    python ocr-model/postprocess/generate_supabase_seed.py
"""
from __future__ import annotations

import json
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CACHE = Path(__file__).parent / "drugs_cache.json"
OUT_DIR = ROOT / "supabase" / "migrations"


def sql_escape(v) -> str:
    """SQL-escape a value (quote strings, NULL for None, raw for bools/numbers)."""
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    s = str(v).replace("'", "''")
    return f"'{s}'"


def main():
    if not CACHE.exists():
        print(f"✗ {CACHE} missing. Run expand_drugs_cache.py first.")
        return

    payload = json.loads(CACHE.read_text(encoding="utf-8"))
    drugs = payload["drugs"]
    print(f"Loaded {len(drugs)} drugs from cache")

    ts = time.strftime("%Y%m%d%H%M%S")
    out_file = OUT_DIR / f"{ts}_seed_drugs_v2.sql"

    cols = ["name_fr", "name_ar", "generic_name", "brand_name", "dosage",
            "form", "manufacturer", "atc_code", "is_generic",
            "cnas_reimbursable", "price_dz"]

    lines = []
    lines.append("-- Auto-generated by ocr-model/postprocess/generate_supabase_seed.py")
    lines.append(f"-- Source: drugs_cache.json (version {payload.get('version','unknown')})")
    lines.append(f"-- Total entries: {len(drugs)}")
    lines.append("--")
    lines.append("-- Run this in Supabase Dashboard → SQL Editor → New query → paste → Run")
    lines.append("-- It DELETEs existing rows then bulk-inserts the full cache.")
    lines.append("")
    lines.append("BEGIN;")
    lines.append("")
    lines.append("-- Relax NOT NULL on all optional columns. Real pharma data is patchy:")
    lines.append("--   - WHO ATC bulk has no Arabic names, brand_name, dosage, manufacturer, atc-only")
    lines.append("--   - Brand-vocab entries have no generic_name or atc_code")
    lines.append("--   - Only name_fr is universally guaranteed.")
    lines.append("ALTER TABLE public.drugs ALTER COLUMN name_ar      DROP NOT NULL;")
    lines.append("ALTER TABLE public.drugs ALTER COLUMN generic_name DROP NOT NULL;")
    lines.append("ALTER TABLE public.drugs ALTER COLUMN brand_name   DROP NOT NULL;")
    lines.append("ALTER TABLE public.drugs ALTER COLUMN dosage       DROP NOT NULL;")
    lines.append("ALTER TABLE public.drugs ALTER COLUMN form         DROP NOT NULL;")
    lines.append("ALTER TABLE public.drugs ALTER COLUMN manufacturer DROP NOT NULL;")
    lines.append("ALTER TABLE public.drugs ALTER COLUMN atc_code     DROP NOT NULL;")
    lines.append("")
    lines.append("-- Wipe existing rows (safe — drugs is reference data, no FK from user-created records)")
    lines.append("DELETE FROM public.drugs;")
    lines.append("")

    BATCH = 200  # PostgreSQL handles 1000+ rows per INSERT but smaller batches are safer
    for i in range(0, len(drugs), BATCH):
        batch = drugs[i:i+BATCH]
        lines.append(f"INSERT INTO public.drugs ({', '.join(cols)}) VALUES")
        rows = []
        for d in batch:
            row_vals = [sql_escape(d.get(c)) for c in cols]
            rows.append("  (" + ", ".join(row_vals) + ")")
        lines.append(",\n".join(rows) + ";")
        lines.append("")

    lines.append("-- Verify")
    lines.append("SELECT COUNT(*) AS drug_count FROM public.drugs;")
    lines.append("")
    lines.append("COMMIT;")
    lines.append("")

    out_file.write_text("\n".join(lines), encoding="utf-8")
    size_kb = out_file.stat().st_size // 1024
    print(f"✓ Wrote {out_file.relative_to(ROOT)}")
    print(f"  {size_kb} KB, {len(drugs)} rows in {(len(drugs)+BATCH-1)//BATCH} INSERT batches")
    print()
    print("Next steps:")
    print("  1. Open Supabase Dashboard → bwtgavgdwihqdlbpystw → SQL Editor → New query")
    print(f"  2. Paste contents of {out_file.name}")
    print("  3. Click Run")
    print("  4. Should see drug_count = " + str(len(drugs)))
    print("  5. Frontend Radar Stock + DCI Switch will now find drugs")


if __name__ == "__main__":
    main()
